---
- hosts: all
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files.sh"
        creates: files
      delegate_to: localhost
      become: false
    - name: Update apt cache
      apt:
        name:
          - python3-apt
        update_cache: true
        state: present
    - name: Run roles
      include_role:
        name: "{{ item }}"
      with_items:
        - docker
        - cache
        - python
        - script
        - homelab
        - hassio
        - logs
