---
- hosts: all
  become: true

  vars_files:
    - config.yml
  
  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files.sh"
        creates: files
      delegate_to: localhost
      become: no
    - name: Include cache
      include_role:
        name: cache
      when: 
        - "lookup('env','ANSIBLECACHE') == '1'"
    - name: Update apt cache
      apt:
        name: python3-apt
        update_cache: true
        state: present
    - name: Install python and pip
      include_role:
        name: python
    - name: Install docker
      include_role:
        name: docker
    - name: Run roles
      include_role:
        name: "{{ item }}"
      with_items:
        - script
        - swap
        - nginx_proxy_manager
        - pill_bot
        # - hassio
