---
- hosts: raspi
  become: true

  vars_files:
    - config.yml
  
  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files"
        creates: files
      delegate_to: localhost
      become: no
    - name: Configure apt proxy
      copy:
        dest: /etc/apt/apt.conf.d/30proxy
        content: 'Acquire::http { Proxy "http://{{ apt_proxy }}:3142"; }'
    - name: Update cache
      apt:
        name: python3-apt
        update_cache: true
        state: present
    - name: Run roles
      include_role:
        name: "{{ item }}"
      loop:
        - python
        - script
        - docker
        - swap
        - nginx-proxy-manager
        # - pill-bot
        - hassio

