---
- hosts: all
  become: true

  vars_files:
    - config.yml
  
  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files.sh"
        creates: files
      delegate_to: localhost
      become: no
    - name: Include cache
      include_role:
        name: cache
      when: ("lookup('env','ANSIBLECACHE') == '1'") or enablecache
    - name: Update apt cache
      apt:
        name: 
          - python3-apt
        update_cache: true
        state: present
    - name: Include python role
      include_role:
        name: python
    - name: Include docker role
      include_role:
        name: docker
    - name: Run roles
      include_role:
        name: "{{ item }}"
      with_items:
        - script
        - nginx_proxy_manager
        # - pill_bot
        # - hassio
