---
- hosts: raspi
  become: true

  vars_files:
    - config.yml
  
  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files"
        creates: files
      delegate_to: localhost
      become: no
    - name: Get check for ANSIBLECACHE
      debug:
        msg: "{{ lookup('env','ANSIBLECACHE') }}"
      delegate_to: localhost
      become: no
      register: ansible_cache
    - name: Include cache
      include_role:
        name: cache
      when: ansible_cache == "1"
    - name: Update cache
      apt:
        name: python3-apt
        update_cache: true
        state: present
    - name: Run roles
      include_role:
        name: "{{ role_name }}"
      loop:
        - python
        - script
        - docker
        - swap
        - nginx_proxy_manager
        # - pill_bot
        - hassio
      loop_control:
        loop_var: role_name
