---
- hosts: all
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Prepare files
      command:
        cmd: "bash get-files.sh"
        creates: files
      delegate_to: localhost
      become: no
    - name: Include cache
      include_role:
        name: cache
      when: enablecache is true
    - name: Update apt cache
      apt:
        name:
          - python3-apt
        update_cache: true
        state: present
    - name: Include python role
      include_role:
        name: python
    - name: Remove x11
      apt:
        name: libx11-6
        state: absent
        purge: true
        autoremove: true
        autoclean: true
      failed_when: false
    - name: Disable swap
      ansible.builtin.systemd:
        name: dphys-swapfile.service
        enabled: false
        state: stopped
    - name: Run roles
      include_role:
        name: "{{ item }}"
      with_items:
        - python
        - docker
        - script
        - logs
        - pill_bot

