---
- name: Install packages
  apt:
    name:
      - "tmux"
      - "curl"
      - "sysstat"
      - "htop"
      - "git"
      - "unzip"
      - "zip"
      - "tar"
      - "vim"
      - "wakeonlan"
    state: present
- name: Allow root login
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#PermitRootLogin without-password"
    line: "PermitRootLogin without-password"
  notify: "Restart ssh"
- name: Disable ssh dns
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#UseDNS no"
    line: "UseDNS no"
- name: Copy ssh dir
  copy:
    src: files/.ssh/
    dest: /root/.ssh
    mode: '600'
- name: Copy priv key
  copy:
    src: files/id_rsa
    dest: /root/.ssh/id_rsa
    mode: '400'
- name: Copy ssh fingerprint
  copy:
    src: files/ssh_host/
    dest: /etc/ssh
  notify: "Restart ssh"
- name: Clone git script
  git:
    repo: "git@github.com:rickycraft/script.git"
    dest: /root/script
- name: Add cron path
  cron:
    name: PATH
    env: true
    job: "/bin:/usr/bin:/sbin:/root/script/hassio:/root/script/bash"
