---
  - name: Copy nginx files
    unarchive:
      src: files/nginx.tar
      dest: /root
  - name: Install nginx service
    copy:
      src: /root/nginx/nginx-proxy-manager.service
      dest: /etc/systemd/system/nginx-proxy-manager.service
      remote_src: true
  - name: Enable nginx service
    systemd:
      daemon_reload: true
      name: nginx-proxy-manager.service
      enabled: true