---
- name: Create docker.service.d dir
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Configure docker proxy
  copy:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    src: files/http-proxy.conf

- name: Install docker proxy cert
  get_url:
    url: "http://{{ apt_proxy }}:3128/ca.crt"
    dest: /usr/share/ca-certificates/docker_registry_proxy.crt
  register: copy_docker_cert

- name: Add docker proxy cert to list
  lineinfile:
    line: docker_registry_proxy.crt
    path: /etc/ca-certificates.conf
  when: copy_docker_cert.changed

- name: Update ca list
  command:
    cmd: update-ca-certificates --fresh
  when: copy_docker_cert.changed

- name: Check if Docker is already present.
  command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
    enabled: true

- name: Install docker-compose using pip
  pip:
    name: docker-compose
    state: present