---
  - name: Install required packages
    apt:
      name:
        - jq
        - curl
        - avahi-daemon
        - udisks2
        - libglib2.0-bin
        - network-manager
        - apparmor
      state: present
  - name: Disable ModemManager
    service:
      name: ModemManager
      enabled: false
      state: stopped
  - name: Install os-agent
    apt:
      deb: "https://github.com/home-assistant/os-agent/releases/download/{{ os_agent_version }}/os-agent_{{ os_agent_version }}_linux_{{ hassio_machine_arch }}.deb"
  - name: Get install script
    get_url:
      url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
      dest: /root
  # - name: Remove NetworkManager config
  #   file:
  #     path: /etc/NetworkManager/NetworkManager.conf
  #     state: absent
  - name: Remove debian network config
    file:
      path: /etc/network/interfaces
      state: absent
    when:
      - ansible_distribution == "Debian"
  - name: Remove configure netplan
    copy:
      src: files/50-cloud-init.yaml
      dest: /etc/netplan/50-cloud-init.yaml
      mode: '600'
    when:
      - ansible_distribution == "Ubuntu"
  - name: Create install dir
    file:
      path: "{{ hassio_data_folder }}/apparmor"
      state: directory
      mode: '0755'
  - name: Get install script
    get_url:
      url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
      dest: /root
  - name: Install homeassistant
    apt:
      deb: /root/homeassistant-supervised.deb
    environment:
      DATA_SHARE: "{{ hassio_data_folder }}"
      MACHINE: "{{ hassio_machine_type }}"